import './globals.css'
import ProviderContext from "@/components/ProviderContext"
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function Layout(props) {
	return (
		<ProviderContext>
			<html lang="en">
				<body className='text-md flex flex-col'>
					<Navbar />
					<div className='min-h-screen'>
						{props.children}
						{props.post}
					</div>

					<Footer />
				</body>
			</html>
		</ProviderContext>
	)
}