export const metadata = {
	title: 'Media Map | Share Image',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<>
			<div className="pt-10 bg-gradient-to-b from-blue-400 to-green-400 ">
				{children}
			</div>

		</>
	)
}